[package]
name = "mind"
version = "0.1.0"
authors = ["horup <sah@sah.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
device_query = "0.1.0"
crossterm = "0.18.2"